apiVersion: v1
kind: Service
metadata:
  name: ghost-qa
  namespace: ghost-qa
  labels:
    app: ghost-qa
spec:
  type: ClusterIP
  selector:
    app: ghost-qa
  ports:
    - name: http
      port: 80
      targetPort: 8000
